account_id = ""
compatibility_date = "2022-06-15"
name = "remix-app-devio2022"

main = "src/index.ts"

workers_dev = true

[site]
bucket = "../../apps/remix-app/public"

[env.dev]
vars = {SESSION_SECRET = "should-be-secure-in-prod"}